### ISSUE TITLE
Bug: Missing tag borders

### ISSUE THREAD

**Issue by SuxianAlicia** [CS2103JAN2018-W13-B1/main#198]
![missing tag borders](https://user-images.githubusercontent.com/35337546/38588480-b7d05e76-3d58-11e8-8ce1-ecb132bf6457.PNG)

Some of the tags do not have borders, and the font color is different in Person Panel.

**Comment by amad-person** [comment]
Perhaps it's the choice of colours that is causing the problem. Maybe we can remove some and check?

**Comment by AJZ1995** [comment]
Resolved
