### ISSUE TITLE
Week 8 Enhancements

### ISSUE THREAD

**Issue by amad-person** [CS2103JAN2018-W13-B1/main#49]
Let's decide what we're going to be working on for v1.1. 
Comment your preferences below, so we can decide what each of us will be doing. Thanks!

**Comment by amad-person** [comment]
I'll be working on #8 mostly.

**Comment by SuxianAlicia** [comment]
I think I’ll work on #31, and continue #20 if I have time. (Unless someone else would like to continue #20

**Comment by AJZ1995** [comment]
Probably #23

**Comment by amad-person** [comment]
Will be opening a new issue for Week 9.
